### ISSUE TITLE
spectral-cli doesn't work on node <= 12.20

### ISSUE THREAD

**Issue by Gerben-T** [stoplightio/spectral#1854]
**Describe the bug**
Error when running spectral cli `Cannot find module 'nimma/legacy'` on node version 12.
[`package.json`](https://github.com/stoplightio/spectral/blob/develop/package.json#L23) says that `node >= 12` is supported, but the [`nimma`](https://github.com/P0lip/nimma) [`package.json`](https://github.com/P0lip/nimma/blob/master/package.json#L14) increases this version to `node >= 12.20`.

**To Reproduce**

1. Install node version 12 (using `.nvmrc` with content `v12` and execute `nvm install`)
2. Install Spectral (`npm install -g @stoplight/spectral-cli`)
3. Run Spectral (`spectral lint somefile.yml`)

**Expected behavior**
Spectral cli should work on the `node` version specified in the `package.json`

**Screenshots**
Spectral error
```
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'nimma/legacy'
```

**Environment (remove any that are not applicable):**
 - Library version: 6.0.0
 - OS: Windows 10
 - Browser: N/A

**Additional context**
N/A

**Comment by P0lip** [comment]
True, I'll change the required version to 12.20.

**Comment by P0lip** [comment]
Changed.
